# Numpy
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

In [79]:
import numpy as np

## Creating Arrays

In [80]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [81]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [82]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print(c)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


## Initial Placeholders

In [83]:
np.zeros((3,4))  #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.ones((2,3,4),dtype=np.int16)   #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [85]:
d = np.arange(10,25,5)   # Create an array of evenly spaced values (step value) 
print(d)

[10 15 20]


In [86]:
np.linspace(0,2,9)    #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [87]:
e = np.full((2,2),7)    # Create a constant array
print(e)

[[7 7]
 [7 7]]


In [88]:
f = np.eye(2)      #Create a 2X2 identity matrix
print(f)

[[1. 0.]
 [0. 1.]]


In [89]:
 np.random.random((2,2))    #Create an array with random values
   

array([[0.35561671, 0.03516917],
       [0.92648708, 0.17509293]])

In [90]:
np.empty((3,2))       #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## Data Types

In [91]:
np.int64   #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool    #Boolean type storing TRUE and FALSE values
np.object  #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

C:\Users\asus\Anaconda3\envs\gee\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\asus\Anaconda3\envs\gee\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removi

numpy.str_

## Inspecting Your Array

In [92]:
a.shape           #Array dimensions

(3,)

In [93]:
len(a)            #Length of array

3

In [94]:
b.ndim            #Number of array dimensions

2

In [95]:
e.size            #Number of array elements

4

In [96]:
b.dtype           #Data type of array elements

dtype('float64')

In [97]:
b.dtype.name      #Name of data type


'float64'

In [98]:
b.astype(int)     #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

## Asking For Help

In [99]:
 np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Arithmetic Operations

In [100]:
g = a - b    #Subtraction
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [101]:
np.subtract(a,b)  #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [102]:
b + a             #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [103]:
np.add(b,a)    #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [104]:
a / b          #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [105]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [106]:
a * b          #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [107]:
np.multiply(a,b)   #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [108]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [109]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [110]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [111]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [112]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [113]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

## Comparison

In [114]:
a == b   #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [115]:
a < 2    #Element-wise comparison

array([ True, False, False])

In [116]:
np.array_equal(a, b) #Array-wise comparison

False

## Aggregate Functions

In [117]:
a.sum() #Array-wise sum

6

In [118]:
a.min() #Array-wise minimum value

1

In [119]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [120]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [121]:
a.mean() #Mean

2.0

In [122]:
np.median(b) #Median

3.5

In [123]:
np.corrcoef(a) #Correlation coefficient

1.0

In [124]:
np.std(b) #Standard deviation

1.5920810978785667

## Copying Arrays

In [125]:
h = a.view()   #Create a view of the array with the same data

In [126]:
np.copy(a) #Create a copy of the array

array([1, 2, 3])

In [127]:
h = a.copy() #Create a deep copy of the array

## Sorting Arrays

In [128]:
a.sort()  #Sort an array

In [129]:
c.sort(axis=0)  #Sort the elements of an array's axis

## Subsetting

In [130]:
a[2]   # Select the element at the 2nd index 3

3

In [131]:
b[1,2] #Select the element at row 1 column 2 (equivalent to b[1][2])

6.0

## Slicing

In [132]:
a[0:2] #Select items at index 0 and 1

array([1, 2])

In [133]:
b[0:2,1] #Select items at rows 0 and 1 in column 1

array([2., 5.])

In [134]:
b[:1] #Select all items at row 0 (equivalent to b[0:1, :])

array([[1.5, 2. , 3. ]])

In [135]:
c[1,...] #Same as [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [136]:
a[ : :-1] #Reversed array a array([3, 2, 1])

array([3, 2, 1])

## Boolean Indexing

In [137]:
a[a<2] #Select elements from a less than 2

array([1])

## Fancy Indexing

In [138]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [139]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Transposing Array

In [140]:
i = np.transpose(b)          #Permute array dimensions

In [141]:
i.T                          #Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Changing Array Shape

In [142]:
b.ravel()                    #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [143]:
g.reshape(3,-2)              #Reshape, but don’t change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## Adding/Removing Elements

In [144]:
h.resize((2,6))              #Return a new array with shape (2,6)

In [145]:
np.append(h,g)               #Append items to an array

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [146]:
np.insert(a, 1, 5)           #Insert items in an array

array([1, 5, 2, 3])

In [147]:
np.delete(a,[1])             #Delete items from an array

array([1, 3])

## Combining Arrays

In [148]:
np.concatenate((a,d),axis=0) #Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [149]:
np.vstack((a,b))             #Stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [150]:
np.r_[e,f]                   #Stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [151]:
np.hstack((e,f))             #Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [152]:
np.column_stack((a,d))       #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [153]:
np.c_[a,d]                   #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

In [154]:
np.hsplit(a,3)               #Split the array horizontally at the 3rd index


[array([1]), array([2]), array([3])]

In [155]:
np.vsplit(c,2)               #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]